using AtomCcompiler.Compiler.Diagnostics;

namespace AtomCcompiler.Compiler.Lexer;

/// <summary>
/// This class contains the output of lexical analysis.
/// </summary>
public sealed class LexerResult
{
    /// <summary>
    /// This constructor stores generated tokens and lexical errors.
    /// </summary>
    public LexerResult(IReadOnlyList<Token> tokens, IReadOnlyList<LexicalError> errors)
    {
        // This line stores every token recognized by the lexer.
        Tokens = tokens;

        // This line stores every lexical diagnostic generated by the lexer.
        Errors = errors;
    }

    /// <summary>
    /// This property exposes the token list.
    /// </summary>
    public IReadOnlyList<Token> Tokens { get; }

    /// <summary>
    /// This property exposes the lexical error list.
    /// </summary>
    public IReadOnlyList<LexicalError> Errors { get; }
}
