using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace AtomCCompiler
{
    /// <summary>
    /// Prints tokens in a readable, compiler-lab-friendly format.
    /// The printer also escapes control characters so strings and chars remain easy to inspect.
    /// </summary>
    public static class TokenPrinter
    {
        /// <summary>
        /// Writes a sequence of tokens to standard output.
        /// </summary>
        /// <param name="tokens">Tokens generated by the lexer.</param>
        public static void Print(IEnumerable<Token> tokens)
        {
            foreach (Token token in tokens)
            {
                Console.WriteLine(Format(token));
            }
        }

        /// <summary>
        /// Builds one formatted output line for a token.
        /// </summary>
        /// <param name="token">Token to format.</param>
        /// <returns>A readable string representation of the token.</returns>
        public static string Format(Token token)
        {
            string text = $"[{token.Type}] \"{EscapeText(token.Lexeme)}\" at line {token.Line}, column {token.Column}";

            // Only literals and identifiers use the Value field, so it is omitted for punctuation and operators.
            if (token.Value is not null)
            {
                text += $" value={FormatValue(token.Value)}";
            }

            return text;
        }

        /// <summary>
        /// Escapes a string so control characters remain visible when printed.
        /// </summary>
        /// <param name="text">Raw text that should be escaped.</param>
        /// <returns>Escaped text ready for terminal output.</returns>
        private static string EscapeText(string text)
        {
            var builder = new StringBuilder();

            foreach (char current in text)
            {
                builder.Append(EscapeCharacter(current, forDoubleQuotedText: true));
            }

            return builder.ToString();
        }

        /// <summary>
        /// Formats the optional token value according to its runtime type.
        /// </summary>
        /// <param name="value">Value stored inside the token.</param>
        /// <returns>A readable value representation.</returns>
        private static string FormatValue(object value)
        {
            if (value is string text)
            {
                return $"\"{EscapeText(text)}\"";
            }

            if (value is char character)
            {
                return $"'{EscapeCharacter(character, forDoubleQuotedText: false)}'";
            }

            if (value is double realNumber)
            {
                return realNumber.ToString("G", CultureInfo.InvariantCulture);
            }

            return Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty;
        }

        /// <summary>
        /// Escapes one character for display.
        /// Double-quoted text escapes double quotes, while character display escapes single quotes.
        /// </summary>
        /// <param name="character">Character that should be escaped.</param>
        /// <param name="forDoubleQuotedText">Controls which quote style needs escaping.</param>
        /// <returns>Escaped text for the character.</returns>
        private static string EscapeCharacter(char character, bool forDoubleQuotedText)
        {
            return character switch
            {
                '\n' => "\\n",
                '\r' => "\\r",
                '\t' => "\\t",
                '\\' => "\\\\",
                '"' when forDoubleQuotedText => "\\\"",
                '\'' when !forDoubleQuotedText => "\\'",
                _ => character.ToString()
            };
        }
    }
}
