using AtomCcompiler.Compiler.Diagnostics;

namespace AtomCcompiler.Compiler.Parser;

/// <summary>
/// This class contains the output of syntax analysis.
/// </summary>
public sealed class ParserResult
{
    /// <summary>
    /// This constructor stores the syntax error list.
    /// </summary>
    public ParserResult(IReadOnlyList<SyntaxError> errors)
    {
        // This line stores every syntax diagnostic generated by the parser.
        Errors = errors;
    }

    /// <summary>
    /// This property exposes the syntax error list.
    /// </summary>
    public IReadOnlyList<SyntaxError> Errors { get; }

    /// <summary>
    /// This property indicates whether parsing completed without syntax errors.
    /// </summary>
    public bool Success => Errors.Count == 0;
}
